/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/computer-optimized.glb -t -o src/components/ContactModels/Computer.tsx 
*/

import * as THREE from 'three'

import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube000_ComputerDesk_0001_1: THREE.Mesh
    Cube000_ComputerDesk_0001_2: THREE.Mesh
  }
  materials: {
    ['ComputerDesk.001']: THREE.MeshStandardMaterial
    ['FloppyDisk.001']: THREE.MeshStandardMaterial
  }
}

export function Computer(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/computer-optimized.glb') as GLTFResult

  const deskMaterial = materials['ComputerDesk.001'].clone()
  deskMaterial.roughness = 0.35
  deskMaterial.metalness = 0.05
  deskMaterial.envMapIntensity = 0.8

  const floppyMaterial = materials['FloppyDisk.001'].clone()
  floppyMaterial.roughness = 0.25
  floppyMaterial.metalness = 0.6
  floppyMaterial.envMapIntensity = 1.5

  return (
    <group {...props} dispose={null}>
      <group position={[-4.005, 67.549, 58.539]}>
        <mesh
          geometry={nodes.Cube000_ComputerDesk_0001_1.geometry}
          material={deskMaterial}
        />
        <mesh
          geometry={nodes.Cube000_ComputerDesk_0001_2.geometry}
          material={floppyMaterial}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/computer-optimized.glb')
