/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/computer-optimized.glb -t -o src/components/ContactModels/Computer.tsx 
*/

import * as THREE from "three";

import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { useRef, type JSX } from "react";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";

type GLTFResult = GLTF & {
  nodes: {
    Cube000_ComputerDesk_0001_1: THREE.Mesh;
    Cube000_ComputerDesk_0001_2: THREE.Mesh;
  };
  materials: {
    ["ComputerDesk.001"]: THREE.MeshStandardMaterial;
    ["FloppyDisk.001"]: THREE.MeshStandardMaterial;
  };
};

export function Computer({
  submitted,
  ...props
}: { submitted: boolean } & JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/computer-optimized.glb",
  ) as unknown as GLTFResult;

  const groupRef = useRef<THREE.Group>(null!);
  const innerRef = useRef<THREE.Group>(null!);

  const deskMaterial = materials["ComputerDesk.001"].clone();
  deskMaterial.roughness = 0.35;
  deskMaterial.metalness = 0.05;
  deskMaterial.envMapIntensity = 0.8;

  const floppyMaterial = materials["FloppyDisk.001"].clone();
  floppyMaterial.roughness = 0.25;
  floppyMaterial.metalness = 0.6;
  floppyMaterial.envMapIntensity = 1.5;

  const ogColor = new THREE.Color(floppyMaterial.color);

  useGSAP(() => {
    if (!submitted) return;

    const tl = gsap.timeline();

    tl.to(groupRef.current.rotation, {
      y: groupRef.current.rotation.y + Math.PI * 2,
      duration: 0.8,
      ease: "power2.out",
    })
      .to(
        groupRef.current.scale,
        { x: 1.08, y: 1.08, z: 1.08, duration: 0.25, ease: "back.out(2)" },
      )
      .to(
        groupRef.current.scale,
        { x: 1, y: 1, z: 1, duration: 0.3, ease: "power2.in" },
      )
      .to(
        floppyMaterial.color,
        { r: 1, g: 0.84, b: 0, duration: 0.35, ease: "power2.out" },
        "-=0.15",
      )
      .to(
        floppyMaterial.color,
        {
          r: ogColor.r,
          g: ogColor.g,
          b: ogColor.b,
          duration: 0.5,
          ease: "power2.inOut",
        },
      );

    return () => {
      tl.kill();
    };
  }, { dependencies: [submitted] });

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group ref={innerRef} position={[-4.005, 67.549, 58.539]} castShadow receiveShadow>
        <mesh
          geometry={nodes.Cube000_ComputerDesk_0001_1.geometry}
          castShadow
          receiveShadow
          material={deskMaterial}
        />
        <mesh
          geometry={nodes.Cube000_ComputerDesk_0001_2.geometry}
          castShadow
          receiveShadow
          material={floppyMaterial}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/computer-optimized.glb");
